### ISSUE TITLE
Scala 2.12 build

### ISSUE THREAD

**Issue by wlk** [ACINQ/bitcoin-lib#11]
Hi,
Do you have any plans to add support for Scala 2.12?
I see that you are using maven to build this project so it's probably a pain to cross-compile, I know that it's fairly straightforward with sbt

**Comment by sstone** [comment]
There is a wip-scala2.12 branch that is not far behind master (and it should be easy to update it) but we do not have plans to support scala 2.12 in the short term.

**Comment by t-bast** [comment]
We jumped directly to Scala 2.13 on the master branch.
