### ISSUE TITLE
Letter "I"

### ISSUE THREAD

**Issue by araspitzu** [ACINQ/bitcoin-lib#3]
Hey did you forget the letter I here?
[https://github.com/ACINQ/bitcoin-lib/blob/master/src/main/scala/fr/acinq/bitcoin/Base58.scala#L30](url)

**Comment by pm47** [comment]
Hello, a few letters are voluntarily omitted in Base58, [more info here](https://en.wikipedia.org/wiki/Base58)
Cheers
