### ISSUE TITLE
console errors like <console>:17: error: not found: value BinaryData

### ISSUE THREAD

**Issue by maxcado** [ACINQ/bitcoin-lib#39]
Hello, I'm new to the scala lang. I've successfully installed this library after trial and error. When inside the scala REPL, the import stuff like import fr.acinq.bitcoin._ and import fr.acinq.bitcoin.Crypto._ works but after that I get the errors like:

scala> val priv = PrivateKey(BinaryData("1e99423a4ed27608a15a2616a2b0e9e52ced330ac530edcc32c8ffc6a526aedd"), compressed = true) results in an error like:
<console>:17: error: not found: value BinaryData
      val priv = PrivateKey(BinaryData("1e99423a4ed27608a15a2616a2b0e9e52ced330ac530edcc32c8ffc6a526aedd"), compressed = true)

There is a ^ at the BinaryData. When inputting all the other samples on the readme page, I get similar error messages.

**Comment by sstone** [comment]
Thank! Samples had not been updated we've replaced BinaryData with scodec's ByteVector
