### ISSUE TITLE
Invalid literal number

### ISSUE THREAD

**Issue by maxcado** [ACINQ/bitcoin-lib#40]
Hello again,
I get an invalid literal number error:
val tx1 = Transaction( version = 1L, txIn = List(TxIn(OutPoint(previousTx, 0), signatureScript = Nil, sequence = 0xFFFFFFFFL) ), txOut = List(TxOut(amount = 054343444, publicKeyScript = OP_DUP :: OP_HASH160 :: OP_PUSHDATA(59343434003038893......) :: OP_EQUALVERIFY :: OP_CHECKSIG :: Nil) ), lockTime = 0L )

I typed all the data on the same line in the shell. Am I putting the pubkeyHash correctly?

Also, can you provide in one of the samples how to put the data in parentheses. For instance, do I put double quotation marks?

**Comment by sstone** [comment]
`054343444` starts with a `0` which is not valid (try entering it in the scala RELP  and see what happens), and amount is in `Satoshi`.

Something like:
``` scala
Transaction( version = 1L, txIn = List(TxIn(OutPoint(tx1.hash, 0), signatureScript = Nil, sequence = 0xFFFFFFFFL) ), txOut = List(TxOut(amount = Satoshi(54343444), publicKeyScript = OP_DUP :: OP_HASH160 :: OP_PUSHDATA(priv1.publicKey.hash160) :: OP_EQUALVERIFY :: OP_CHECKSIG :: Nil) ), lockTime = 0L )
```
should work.
