### ISSUE TITLE
Create lnurl with Bech32

### ISSUE THREAD

**Issue by theborakompanioni** [ACINQ/bitcoin-lib#56]
I want to create an lnurl string following [lnurl rfc](https://github.com/fiatjaf/lnurl-rfc).

Decoding is possible with
```scala
import fr.acinq.bitcoin.Bech32

val bech32lnurl: String = "LNURL1DP68GURN8GHJ7UM9WFMXJCM99E3K7MF0V9CXJ0M385EKVCENXC6R2C35XVUKXEFCV5MKVV34X5EKZD3EV56NYD3HXQURZEPEXEJXXEPNXSCRVWFNV9NXZCN9XQ6XYEFHVGCXXCMYXYMNSERXFQ5FNS"

val (hrp, dataPart) = Bech32.decode(bech32lnurl)
val requestByteArray = Bech32.five2eight(dataPart)

new String(requestByteArray, "UTF-8") // https://service.com/api?q=3fc3645b439ce8e7f2553a69e5267081d96dcd340693afabe04be7b0ccd178df
```

.. but I seem to fail encoding an url because the `eight2five` method in `Bech32` is not publicly visible.

https://github.com/ACINQ/bitcoin-lib/blob/eac7415995525ce2204863a3cb3954bb1edb31e4/src/main/scala/fr/acinq/bitcoin/Bech32.scala#L101

Am I missing something? Sorry if this is a misunderstanding on my end. Can you guide me into the right direction?

**Comment by sstone** [comment]
Yes in our apps we just need to decode LNURL strings, not create them. `eight2five()` is a bit ugly but since ` five2eight()` is already public we could make it public too.

**Comment by theborakompanioni** [comment]
@sstone It is trivial to be implemented by any library using bitcoin-lib.. [SimpleLnurl.java#L65-L93](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/6ab1caa8f268d7ee20e5fd8010e5c7b418a2adac/incubator/lnurl-java/lnurl-simple/src/main/java/org/tbk/lnurl/simple/SimpleLnurl.java#L65-L93)

.. but since it is already there.. I guess the function would appreciate being made public. Than it has a purpose.. a meaning.. it can shine. You'd really make that function very happy : D
And me too.

**Comment by t-bast** [comment]
That sounds reasonable, feel free to send a PR that makes this function public and we'll integrate it.
